name=TM1637_6Easy
version=1.0.0
author=Sergey Nikolaevich <gray_wolf19@mail.ru>
maintainer=Sergey Nikolaevich <gray_wolf19@mail.ru>
sentence=High-performance library for 6-digit LED displays based on TM1637 driver.
paragraph=Minimalistic and fast library for TM1637 6-digit displays with direct port I/O.
category=Display
url=https://github.com/klenov1900-lang/TM1637_6Easy
architectures=avr
